# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2020-08-01 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ssurlurl',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='ssurlurl',
            name='shorturl',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
