# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2020-08-03 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0002_auto_20200801_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ssurlurl',
            name='shorturl',
            field=models.CharField(blank=True, default='abs', max_length=10, unique=True),
        ),
    ]
