# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2020-08-12 05:25
from __future__ import unicode_literals

from django.db import migrations, models
import shortner.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0003_auto_20200803_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ssurlurl',
            name='url',
            field=models.CharField(max_length=220, validators=[shortner.validators.validate_url, shortner.validators.validate_dot_com]),
        ),
    ]
