# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2020-08-12 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0004_auto_20200812_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ssurlurl',
            name='shorturl',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
