# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2020-08-13 03:22
from __future__ import unicode_literals

from django.db import migrations, models
import shortner.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0005_auto_20200812_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ssurlurl',
            name='url',
            field=models.CharField(max_length=220, validators=[shortner.validators.validate_url]),
        ),
    ]
